replicaCount: 1
nexus:
  service:
    type: ClusterIP
  nexusPort: 8081
  additionalPorts:
  - 8081
ingress:
  enabled: true
  path: /
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    enabled: true
    secretName: nexus-tls
