images:
  registry: "gcr.io/cb-thunder-v2"
  imageRepository: "k8s-agent"
  tag: "v4"
  pullPolicy: Always
resourceName: "k8s-agent"
resourcePools: "kubectl"
zoneName: "default"
flowCredentials:
  user: admin
  password: changeme
storage:
  volumes:
    agentWorkspace:
      accessMode: ReadWriteMany
      storageClass: nfs
