images:
  registry: "gcr.io/core-flow-research"
  imageRepository: "k8s-agent"
  tag: "10.9.0.157496_3.2.22_20220929"
  pullPolicy: Always
resourceName: "k8s-agent"
resourcePools: "kubectl"
zoneName: "default"
flowCredentials:
  user: admin
  password: changeme
storage:
  volumes:
    agentWorkspace:
      accessMode: ReadWriteMany
      storageClass: nfs
