controller:
  admissionWebhooks:
    port: 8445
  config:
    proxy-stream-timeout: "4000s"

  ingressClassResource:
    name: nginx
    default: true
tcp:
  # "7800": cloudbees-sda/gateway-external-agent-flow-agents:7800
  "8200": cloudbees-sda/flow-repository:8200
  "8443": cloudbees-sda/flow-server:8443
  # If you need to expose DOIS externally you can enable these, but you may run into issues in GCP
  # "9200": cloudbees-sda/flow-devopsinsight:9200
  # "9500": cloudbees-sda/flow-devopsinsight:9500
  "61613": cloudbees-sda/flow-server:61613
