apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cjoc-cm-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
      - watch
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cjoc-cm-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cjoc-cm-role
subjects:
  - kind: ServiceAccount
    name: cjoc
