artifactory:
  nginx:
    enabled: false
  ingress:
    enabled: true
    hosts: []
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls:
      - secretName: artifactory-tls
        hosts: []
  admin:
    ip: "*"
    username: admin

