OperationsCenter:
  Enabled: true
  Platform: gke
  HostName: null
  Ingress:
    Class: nginx
    Annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls:
      Enable: true
      SecretName: ci-tls

  ExtraGroovyConfiguration:
    z-quickstart-hook.groovy:

  ExtraVolumes:
    - name: init-groovy
      configMap:
        name: cbci-oc-init-groovy
        defaultMode: 420
    - name: quickstart-groovy
      configMap:
        name: cbci-oc-quickstart-groovy
        defaultMode: 420

  ExtraVolumeMounts:
    - name: init-groovy
      mountPath: /var/jenkins_config/init.groovy.d
      readOnly: true
    - name: quickstart-groovy
      mountPath: /var/jenkins_home/quickstart.groovy.d
      readOnly: true


Persistence:
  Size: 20Gi

Hibernation:
  Enabled: true

## Install Default RBAC roles and bindings
rbac:
  # rbac.install -- Install `role`/`rolebindings`/`serviceAccount`.
  # If false (and rbac is enabled in the cluster anyway), provide valid names for all service accounts.
  install: true

  # rbac.installCluster -- Install `clusterrole`/`clusterrolebinding`
  # These cluster roles are optional but prevent usage of some features, so we recommend setting them up.
  # Defaults to true, except on Openshift 3 where it defaults to false
  # Please refer to templates/cjoc-clusterrole-master-management.yaml in the chart
  #installCluster: true

  # rbac.serviceAccountName -- Name of the service account Operations Center will run as
  serviceAccountName: cjoc
  # rbac.masterServiceAccountName -- Name of the service account Jenkins masters will run as
  masterServiceAccountName: jenkins
  # rbac.agentServiceAccountName -- Name of the service account Jenkins agents will run as
  agentsServiceAccountName: jenkins-agents
  # rbac.hibernationMonitorServiceAccountName -- Name of the service account the Hibernation monitor will run as (if enabled)
  hibernationMonitorServiceAccountName: managed-master-hibernation-monitor
